#!/bin/bash
# mise description="Deploys the website"

set -euo pipefail

pnpm -C $MISE_PROJECT_ROOT exec astro build
cat <<EOT > $MISE_PROJECT_ROOT/dist/_redirects
https://tuist.io/* -> https://tuist.dev/:splat 301
http://tuist.io/* -> https://tuist.dev/:splat 301
EOT
pnpm -C $MISE_PROJECT_ROOT exec wrangler pages deploy dist --project-name tuist-website --branch main