name: Deploy
on:
  push:
    branches:
      - 'main'

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
  
env:
    MISE_EXPERIMENTAL: 1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: jdx/mise-action@v2

      - name: Install Mise dependencies
        uses: jdx/mise-action@v2

      - name: Install project dependencies
        run: mise run install

      - name: Build
        run: mise run build